"""remove user_id from schedules

Revision ID: d858d84aa1dc
Revises: 23e498e6b249
Create Date: 2025-01-06 00:35:42.327388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd858d84aa1dc'
down_revision = '23e498e6b249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('user_id')
       

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###
